run('../setup_analysis.m');
%% load x1D
W_lp.loop('function_simulate_games', ...
    {'x1D_t0t1000_svm', 'data_cleaned', 'sub', 'model1D_t0t1000_svm_scaledEV_npool1'}, ...
    'simudata_model1D_t0t1000_svm_scaledEV_npool1');
