run('../setup_analysis.m')
%%
% W_lp.set_loopsfx('t0t1000', 'svm'); 
% W_lp.parloopsfx('function_model_2population', {'x1D_autosfx2', 'pca_autosfx1', ...
%     'data_cleaned', ...
%     'anova_pos_neg', 'sub'}, ...
%     'model2P');