function plt = setup_plot(figdir)
    figdir = W.get_fullpath(figdir);
    plt = W_plt('savedir', figdir, ...
        'issave', true, 'extension', {'svg','jpg'}, ...
        'isshow', true);
    plt.set_custom_variables('color_monkeys', {'AZred', 'AZblue'}, ...
        'color_rejectaccept', {'RSgreen', 'RSred'}, ...
        'color_anova', {'RSred','AZcactus','AZsand','AZsky'}, ...
        'name_monkeys', {'Monkey W', 'Monkey V'});
end